# Generated by Django 5.2.4 on 2025-12-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_arbeitsgruppe_mitarbeiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitarbeiter',
            name='arbeitsgruppe',
        ),
        migrations.DeleteModel(
            name='Arbeitsgruppe',
        ),
        migrations.DeleteModel(
            name='Mitarbeiter',
        ),
    ]
