# Generated by Django 5.2.4 on 2026-01-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_mitarbeiter_arbeitsgruppe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbeitsgruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameDerArbeitsgruppe', models.CharField(max_length=200)),
                ('Kostenstelle', models.IntegerField()),
            ],
        ),
    ]
