# Generated by Django 5.2.4 on 2026-01-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
