# Generated by Django 5.2.4 on 2026-01-06 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_arbeitsgruppe'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.arbeitsgruppe'),
            preserve_default=False,
        ),
    ]
