# Generated by Django 5.2.4 on 2026-01-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_ag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbeitsgruppe',
            old_name='NameDerArbeitsgruppe',
            new_name='Name',
        ),
    ]
